### PR TITLE
Add 11.405 to external link list

### PR DESCRIPTION
**Pull request by pdpinch**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

None. But I noticed the external link was missing from https://ocwnext-rc.odl.mit.edu/courses/11-405-just-money-banking-as-if-society-mattered-spring-2021/

#### What's this PR do?

Hopefully adds the external link. 

#### How should this be manually tested?

We'll need to build the course and see what it looks like.

### CODE REVIEW

**Comment by pdpinch** [comment]
I haven't tested this locally, but if anyone has simple instructions to do so, I will give it a shot.

**Review by gumaerc — APPROVED** [review]
👍 LGTM

image

**Comment by pdpinch** [comment]
Hm. I don’t think that “syllabus” is supposed to be there though. It’s not on https://ocw.mit.edu/courses/urban-studies-and-planning/11-405-just-money-banking-as-if-society-mattered-spring-2021/

Anyway, unrelated to this PR.

**Comment by gumaerc** [comment]
@pdpinch It's in the parsed JSON for that course, but the content is blank:

```
        {
            "order_index": null,
            "uid": "42302a80a779eca6385816bd7c7a6bf1",
            "parent_uid": "582eb8f5f39dfebe0aef874da6a2623e",
            "title": "Syllabus",
            "short_page_title": "Syllabus",
            "text": "",
            "url": "/courses/urban-studies-and-planning/11-405-just-money-banking-as-if-society-mattered-spring-2021/syllabus",
            "short_url": "syllabus",
            "description": "",
            "type": "CourseSection",
            "is_image_gallery": false,
            "is_media_gallery": false,
            "list_in_left_nav": false,
            "file_location": "42302a80a779eca6385816bd7c7a6bf1_syllabus.html",
            "bottomtext": ""
        }
```

image

Maybe something was unintentionally published in Plone?

**Pull request merged**
