### PR TITLE
popup video links

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
https://github.com/mitodl/ocw-to-hugo/issues/235

#### What's this PR do?
Recently the `template_type` property was added to items in `course_embedded_media` in OCW parsed JSON.  This PR looks for items with a `template_type` of `popup` and instead of writing in an embedded video, a link to the single video player page is written in.

#### How should this be manually tested?
 - Read the readme if you have not used this utility before
 - Generate markdown for a course that has popup type videos, such as `18-03sc-differential-equations-fall-2011` or `21g-107-chinese-i-streamlined-fall-2014`
 - Verify that popup type videos have a link rendered instead of an embedded video, and that the link leads to the page for that video

Some examples of pages with popup type videos in `18-03sc-differential-equations-fall-2011` can be found in `content/sections/unit-i-first-order-differential-equations/solution-by-integrating-factors/`

### CODE REVIEW

**Comment by noisecapella** [comment]
I'm not seeing a difference in `18-01sc-single-variable-calculus-fall-2010` which was mentioned in the issue. Are the videos there not popup videos or otherwise not addressed by this issue?

**Comment by gumaerc** [comment]
@noisecapella I just looked at the parsed JSON for that couse on `open-learning-course-data-production` and none of the `course_embedded_media` items have the `template_type` property.  I'm looking into that and will get back to you.

**Comment by gumaerc** [comment]
@noisecapella So it seems there are two things going on here.  That course's parsed JSON on `open-learning-course-data-production` does indeed seem to be out of date.  Lots of other courses were updated with the `template_type` keys, but that one was not for some reason that I'm unsure of.  I ran the course through `ocw-data-parser` locally and it has the `template_type` tags in the output.  This brings me to the second problem, which is that there's an additional `template_type` that needs to be handled here: `thumbnail_popup`.

**Comment by gumaerc** [comment]
@noisecapella This is technically ready to go, although I haven't been able to run a `backpopulate_ocw_data` yet because the Open reindex that's pending hasn't finished yet.  If you want to test 18-01sc, I uploaded my manually parsed JSON here: 

https://gist.github.com/gumaerc/3d8e5276fccd0cbfb4669a8e3bb3b566

You can also test any other course you'd like by manually running it through `ocw-data-parser` yourself.

**Review by noisecapella — APPROVED** [review]

**Pull request merged**
